#!/usr/bin/env python3
"""Generate a per-sample HTCondor DAG for sharded assocPV merge jobs."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


DAG_HEADER = """\
# ==============================================================================
# Auto-generated assocPV merge DAG for {tag}  ({n_shards} shard jobs)
# ==============================================================================
#
# Pipeline: shard jobs -> ROOT merge
# Generated by generate_assoc_merge_dag.py
#
"""


SHARD_SUB_TEMPLATE = """\
# assocPV merge shard {shard_index} for {tag}
universe = vanilla
executable = ./run_wrapper.sh

arguments = "{arguments}"

log_dir = logs/assoc_merge
output = $(log_dir)/assoc_merge_{tag}_{shard_index}_$(Cluster)_$(Process).out
error  = $(log_dir)/assoc_merge_{tag}_{shard_index}_$(Cluster)_$(Process).err
log    = $(log_dir)/assoc_merge_{tag}_{shard_index}_$(Cluster).log

+JobFlavour = "{flavor}"

request_cpus = {jobs}
request_memory = {memory}
request_disk = {disk}

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = {runtime_tarball}

getenv = False
environment = "LCG_VIEW=/cvmfs/sft.cern.ch/lcg/views/LCG_109a/x86_64-el9-gcc13-opt RUNTIME_TARBALL={runtime_tarball_basename}"

use_x509userproxy = True
x509userproxy = /afs/cern.ch/user/c/chiw/condor/x509up

notification = Error
notify_user = chiw@cern.ch

requirements = (OpSysAndVer =?= "AlmaLinux9")

Queue 1
"""


POST_SUB_TEMPLATE = """\
# assocPV merge post-processing for {tag}
universe = vanilla
executable = ./run_wrapper.sh

arguments = "run_assoc_merge_post.sh {merge_plan}"

log_dir = logs/assoc_merge
output = $(log_dir)/post_{tag}_$(Cluster).out
error  = $(log_dir)/post_{tag}_$(Cluster).err
log    = $(log_dir)/post_{tag}_$(Cluster).log

+JobFlavour = "{flavor}"

request_cpus = {post_jobs}
request_memory = {memory}
request_disk = {disk}

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = {runtime_tarball}

getenv = False
environment = "LCG_VIEW=/cvmfs/sft.cern.ch/lcg/views/LCG_109a/x86_64-el9-gcc13-opt RUNTIME_TARBALL={runtime_tarball_basename}"

use_x509userproxy = True
x509userproxy = /afs/cern.ch/user/c/chiw/condor/x509up

notification = Error
notify_user = chiw@cern.ch

requirements = (OpSysAndVer =?= "AlmaLinux9")

Queue 1
"""


def read_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def _shard_args(
    *,
    channel: str,
    dataset: str,
    sample: str | None,
    shard_index: str,
    manifest_path: str,
    output_path: str,
    jobs: str,
    max_events: str,
    muon_id: str,
    jpsi_muon_id: str,
    ups_muon_id: str,
) -> str:
    sample_arg = f"--sample {sample} " if sample else ""
    return (
        f"run_assoc_merge_shard.sh "
        f"--channel {channel} "
        f"--dataset {dataset} "
        f"{sample_arg}"
        f"--shard-index {shard_index} "
        f"--shard-manifest {manifest_path} "
        f"--output {output_path} "
        f"-j {jobs} "
        f"-n {max_events} "
        f"--muon-id {muon_id} "
        f"--jpsi-muon-id {jpsi_muon_id} "
        f"--ups-muon-id {ups_muon_id}"
    )


def build_dag(
    *,
    queue_file: Path,
    runtime_tarball: str,
    dag_dir: Path,
    jobs: str,
    max_events: str,
    muon_id: str,
    jpsi_muon_id: str,
    ups_muon_id: str,
    flavor: str,
    memory: str,
    disk: str,
    post_flavor: str,
    post_jobs: str,
    post_memory: str,
    post_disk: str,
) -> Path:
    if not queue_file.exists():
        raise FileNotFoundError(f"Queue file not found: {queue_file}")
    merge_plan = queue_file.parent / "merge_plan.json"
    if not merge_plan.exists():
        raise FileNotFoundError(f"Merge plan not found: {merge_plan}")

    plan = read_json(merge_plan)
    tag = str(plan["tag"])
    channel = str(plan["channel"])
    dataset = str(plan["dataset"])
    sample = plan.get("sample")
    if sample is not None:
        sample = str(sample)

    shard_entries: list[tuple[str, str, str]] = []
    for line in queue_file.read_text(encoding="utf-8").strip().splitlines():
        parts = line.strip().split(None, 3)
        if len(parts) < 4:
            continue
        if parts[0] == tag:
            shard_entries.append((parts[1], parts[2], parts[3]))
    if not shard_entries:
        raise RuntimeError(f"No shard entries found for {tag} in {queue_file}")

    dag_dir.mkdir(parents=True, exist_ok=True)
    tarball_basename = Path(runtime_tarball).name
    dag_path = dag_dir / f"dag_assoc_merge_{tag}.dag"
    lines: list[str] = [DAG_HEADER.format(tag=tag, n_shards=len(shard_entries))]

    shard_names: list[str] = []
    for shard_index, manifest_path, output_path in shard_entries:
        shard_name = f"SHARD_{shard_index.zfill(4)}"
        shard_names.append(shard_name)
        sub_path = (dag_dir / f"sub_assoc_merge_{tag}_{shard_index.zfill(4)}.sub").resolve()
        sub_path.write_text(
            SHARD_SUB_TEMPLATE.format(
                tag=tag,
                shard_index=shard_index,
                arguments=_shard_args(
                    channel=channel,
                    dataset=dataset,
                    sample=sample,
                    shard_index=shard_index,
                    manifest_path=manifest_path,
                    output_path=output_path,
                    jobs=jobs,
                    max_events=max_events,
                    muon_id=muon_id,
                    jpsi_muon_id=jpsi_muon_id,
                    ups_muon_id=ups_muon_id,
                ),
                flavor=flavor,
                jobs=jobs,
                memory=memory,
                disk=disk,
                runtime_tarball=runtime_tarball,
                runtime_tarball_basename=tarball_basename,
            ),
            encoding="utf-8",
        )
        lines.append(f"JOB {shard_name} {sub_path}")
        lines.append("")

    post_sub = (dag_dir / f"sub_assoc_merge_post_{tag}.sub").resolve()
    post_sub.write_text(
        POST_SUB_TEMPLATE.format(
            tag=tag,
            merge_plan=merge_plan,
            flavor=post_flavor,
            post_jobs=post_jobs,
            memory=post_memory,
            disk=post_disk,
            runtime_tarball=runtime_tarball,
            runtime_tarball_basename=tarball_basename,
        ),
        encoding="utf-8",
    )
    lines.append(f"JOB POST {post_sub}")
    lines.append("")
    lines.append("PARENT " + " ".join(shard_names) + " CHILD POST")
    lines.append("")

    dag_path.write_text("\n".join(lines), encoding="utf-8")
    return dag_path


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate sharded assocPV merge DAG")
    parser.add_argument("--queue-file", required=True)
    parser.add_argument("--runtime-tarball", required=True)
    parser.add_argument("--dag-dir", default=None)
    parser.add_argument("--jobs", default="2")
    parser.add_argument("--max-events", default="-1")
    parser.add_argument("--muon-id", default="soft")
    parser.add_argument("--jpsi-muon-id", default="soft")
    parser.add_argument("--ups-muon-id", default="soft")
    parser.add_argument("--flavor", default="workday")
    parser.add_argument("--memory", default="6000")
    parser.add_argument("--disk", default="10G")
    parser.add_argument("--post-flavor", default="workday")
    parser.add_argument("--post-jobs", default="2")
    parser.add_argument("--post-memory", default="6000")
    parser.add_argument("--post-disk", default="10G")
    args = parser.parse_args()

    queue_file = Path(args.queue_file)
    dag_dir = Path(args.dag_dir) if args.dag_dir else (queue_file.parent / "dags")
    dag_path = build_dag(
        queue_file=queue_file,
        runtime_tarball=args.runtime_tarball,
        dag_dir=dag_dir,
        jobs=args.jobs,
        max_events=args.max_events,
        muon_id=args.muon_id,
        jpsi_muon_id=args.jpsi_muon_id,
        ups_muon_id=args.ups_muon_id,
        flavor=args.flavor,
        memory=args.memory,
        disk=args.disk,
        post_flavor=args.post_flavor,
        post_jobs=args.post_jobs,
        post_memory=args.post_memory,
        post_disk=args.post_disk,
    )
    print(f"Wrote DAG: {dag_path}")


if __name__ == "__main__":
    main()
