#!/usr/bin/env python3
"""Generate a per-sample HTCondor DAG for the efficiency pipeline.

Reads the master queue file produced by prepare_efficiency_shards.py,
filters to the target sample, and writes a DAG with per-node submit files
(no VARS — all values hardcoded, consistent with the FASER calibration pattern).

    N × SHARD_job -> POST -> optional CLEANUP

Usage:
    python3 generate_efficiency_dag.py \\
        --sample JJP_DPS2_CS \\
        --queue-file /path/to/jjp_efficiency_queue.txt \\
        --output-dir /eos/user/c/chiw/.../efficiency \\
        --runtime-tarball /path/to/tarball.tar.gz \\
        --dag-dir /path/for/dag/output \\
        [--cleanup-shards]
"""

from __future__ import annotations

import argparse
from pathlib import Path

DAG_HEADER = """\
# ==============================================================================
# Auto-generated DAG for {sample}  ({n_shards} shard jobs)
# ==============================================================================
#
# Pipeline: shard jobs -> merge+plot -> {cleanup_line}
# Generated by generate_efficiency_dag.py
#
"""

SHARD_SUB_TEMPLATE = """\
# shard {shard_index} for {sample}
universe = vanilla
executable = ./run_wrapper.sh

arguments = "{arguments}"

log_dir = logs/jjp_efficiency
output = $(log_dir)/jjp_efficiency_{sample}_{shard_index}_$(Cluster)_$(Process).out
error  = $(log_dir)/jjp_efficiency_{sample}_{shard_index}_$(Cluster)_$(Process).err
log    = $(log_dir)/jjp_efficiency_{sample}_{shard_index}_$(Cluster).log

+JobFlavour = "microcentury"

request_memory = 8000
request_cpus = 1
request_disk = 5G

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = {runtime_tarball}

getenv = False
environment = "LCG_VIEW=/cvmfs/sft.cern.ch/lcg/views/LCG_109a/x86_64-el9-gcc13-opt RUNTIME_TARBALL={runtime_tarball_basename}"

use_x509userproxy = True
x509userproxy = /afs/cern.ch/user/c/chiw/condor/x509up

notification = Error
notify_user = chiw@cern.ch

requirements = (OpSysAndVer =?= "AlmaLinux9")

Queue 1
"""

POST_SUB_TEMPLATE = """\
# post-processing for {sample}
universe = vanilla
executable = ./run_wrapper.sh

arguments = "run_jjp_efficiency_post.sh {sample} {shards_dir} {output_dir}"

log_dir = logs/jjp_efficiency
output = $(log_dir)/post_{sample}_$(Cluster).out
error  = $(log_dir)/post_{sample}_$(Cluster).err
log    = $(log_dir)/post_{sample}_$(Cluster).log

+JobFlavour = "microcentury"

request_memory = 8000
request_cpus = 1
request_disk = 5G

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = {runtime_tarball}

getenv = False
environment = "LCG_VIEW=/cvmfs/sft.cern.ch/lcg/views/LCG_109a/x86_64-el9-gcc13-opt RUNTIME_TARBALL={runtime_tarball_basename}"

use_x509userproxy = True
x509userproxy = /afs/cern.ch/user/c/chiw/condor/x509up

notification = Error
notify_user = chiw@cern.ch

requirements = (OpSysAndVer =?= "AlmaLinux9")

Queue 1
"""

CLEANUP_SUB_TEMPLATE = """\
# cleanup shards for {sample}
universe = vanilla
executable = ./run_wrapper.sh

arguments = "run_jjp_efficiency_cleanup.sh {sample} {shards_dir} {output_dir}"

log_dir = logs/jjp_efficiency
output = $(log_dir)/cleanup_{sample}_$(Cluster).out
error  = $(log_dir)/cleanup_{sample}_$(Cluster).err
log    = $(log_dir)/cleanup_{sample}_$(Cluster).log

+JobFlavour = "espresso"

request_memory = 2000
request_cpus = 1
request_disk = 1G

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = {runtime_tarball}

getenv = False
environment = "LCG_VIEW=/cvmfs/sft.cern.ch/lcg/views/LCG_109a/x86_64-el9-gcc13-opt RUNTIME_TARBALL={runtime_tarball_basename}"

use_x509userproxy = True
x509userproxy = /afs/cern.ch/user/c/chiw/condor/x509up

notification = Error
notify_user = chiw@cern.ch

requirements = (OpSysAndVer =?= "AlmaLinux9")

Queue 1
"""


def _shard_args(sample: str, shard_index: str, manifest_path: str, output_dir: str,
                remote_access_mode: str, efficiency_backend: str,
                stage_retries: str, copy_timeout: str,
                worker_timeout: str) -> str:
    return (
        f"run_jjp_efficiency_shard.sh "
        f"--sample {sample} "
        f"--shard-index {shard_index} "
        f"--shard-manifest {manifest_path} "
        f"--output-dir {output_dir} "
        f"--remote-access-mode {remote_access_mode} "
        f"--efficiency-backend {efficiency_backend} "
        f"--stage-retries {stage_retries} "
        f"--copy-timeout {copy_timeout} "
        f"--worker-timeout {worker_timeout} "
        f"--skip-plots"
    )


def build_dag(
    sample: str,
    queue_file: Path,
    output_dir: Path,
    runtime_tarball: str,
    dag_dir: Path,
    *,
    cleanup_shards: bool = False,
    remote_access_mode: str = "fallback",
    efficiency_backend: str = "vectorized",
    stage_retries: str = "3",
    copy_timeout: str = "180",
    worker_timeout: str = "180",
) -> Path:
    if not queue_file.exists():
        raise FileNotFoundError(f"Queue file not found: {queue_file}")

    dag_dir.mkdir(parents=True, exist_ok=True)
    output_dir = output_dir.rstrip("/")

    # Parse master queue file, filter to target sample
    shard_entries: list[tuple[str, str]] = []
    for line in queue_file.read_text().strip().splitlines():
        parts = line.strip().split(None, 2)
        if len(parts) < 3:
            continue
        if parts[0] == sample:
            shard_entries.append((parts[1], parts[2]))

    if not shard_entries:
        raise RuntimeError(f"No shard entries found for sample {sample} in {queue_file}")

    tarball_basename = Path(runtime_tarball).name
    shards_dir = f"{output_dir}/shards/{sample}"
    dag_path = dag_dir / f"dag_{sample}.dag"
    cleanup_note = "cleanup" if cleanup_shards else "done (no cleanup)"
    header = DAG_HEADER.format(sample=sample, n_shards=len(shard_entries),
                                cleanup_line=cleanup_note)

    lines: list[str] = [header]

    # Write per-shard submit files and DAG entries
    shard_names: list[str] = []
    for shard_index, manifest_path in shard_entries:
        name = f"SHARD_{shard_index.zfill(4)}"
        shard_names.append(name)
        sub_path = (dag_dir / f"sub_shard_{sample}_{shard_index.zfill(4)}.sub").resolve()
        sub_path.write_text(SHARD_SUB_TEMPLATE.format(
            sample=sample,
            shard_index=shard_index,
            arguments=_shard_args(
                sample, shard_index, manifest_path, output_dir,
                remote_access_mode, efficiency_backend,
                stage_retries, copy_timeout, worker_timeout,
            ),
            runtime_tarball=runtime_tarball,
            runtime_tarball_basename=tarball_basename,
        ))
        lines.append(f"JOB {name} {sub_path}")
        lines.append("")

    # POST submit file
    post_sub = (dag_dir / f"sub_post_{sample}.sub").resolve()
    post_sub.write_text(POST_SUB_TEMPLATE.format(
        sample=sample,
        shards_dir=shards_dir,
        output_dir=output_dir,
        runtime_tarball=runtime_tarball,
        runtime_tarball_basename=tarball_basename,
    ))
    lines.append(f"JOB POST {post_sub}")
    lines.append("")
    lines.append("PARENT " + " ".join(shard_names) + " CHILD POST")
    lines.append("")

    # CLEANUP submit file (optional)
    if cleanup_shards:
        cleanup_sub = (dag_dir / f"sub_cleanup_{sample}.sub").resolve()
        cleanup_sub.write_text(CLEANUP_SUB_TEMPLATE.format(
            sample=sample,
            shards_dir=shards_dir,
            output_dir=output_dir,
            runtime_tarball=runtime_tarball,
            runtime_tarball_basename=tarball_basename,
        ))
        lines.append(f"JOB CLEANUP {cleanup_sub}")
        lines.append("")
        lines.append("PARENT POST CHILD CLEANUP")
        lines.append("")

    dag_path.write_text("\n".join(lines))
    return dag_path


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate per-sample HTCondor DAG for the efficiency pipeline"
    )
    parser.add_argument("--sample", required=True, help="Sample key (e.g. JJP_DPS2_CS)")
    parser.add_argument("--queue-file", required=True, help="Master queue file from prepare_efficiency_shards.py")
    parser.add_argument("--output-dir", required=True, help="Efficiency output base directory")
    parser.add_argument("--runtime-tarball", required=True, help="Path to runtime tarball")
    parser.add_argument("--dag-dir", default=None, help="Directory for DAG output (default: <queue-file parent>/dags)")
    parser.add_argument("--cleanup-shards", action="store_true", help="Add a cleanup job to remove shard dirs after successful merge")
    parser.add_argument("--remote-access-mode", default="fallback")
    parser.add_argument("--efficiency-backend", default="vectorized")
    parser.add_argument("--stage-retries", default="3")
    parser.add_argument("--copy-timeout", default="180")
    parser.add_argument("--worker-timeout", default="180")
    args = parser.parse_args()

    queue_file = Path(args.queue_file)
    dag_dir = Path(args.dag_dir) if args.dag_dir else (queue_file.parent / "dags")
    dag_path = build_dag(
        sample=args.sample,
        queue_file=queue_file,
        output_dir=args.output_dir.rstrip("/"),
        runtime_tarball=args.runtime_tarball,
        dag_dir=dag_dir,
        cleanup_shards=args.cleanup_shards,
        remote_access_mode=args.remote_access_mode,
        efficiency_backend=args.efficiency_backend,
        stage_retries=args.stage_retries,
        copy_timeout=args.copy_timeout,
        worker_timeout=args.worker_timeout,
    )
    print(f"Wrote DAG: {dag_path}")


if __name__ == "__main__":
    main()
