#!/usr/bin/env python3
"""Generate a safe, per-sample HTCondor DAG for JJP efficiency shards.

The generated DAG ends after a strict merge.  Derived maps, plots, closure and
yield work belong to the downstream hepthu stage. ``--output-dir`` is a
campaign root, and each sample is merged into ``<output-dir>/<sample>`` so
independent POST nodes cannot race on top-level merge metadata.
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import re
import shlex


REPO_ROOT = Path(__file__).resolve().parents[1]
_SAFE_TOKEN = re.compile(r"^[A-Za-z0-9_./:=+@%-]+$")
_SAFE_NAME = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_.-]*$")
_SAFE_SAMPLE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_]*$")

DAG_HEADER = """\
# ==============================================================================
# Auto-generated JJP efficiency DAG for {sample} ({n_shards} shard jobs)
# ==============================================================================
# Pipeline: shard jobs -> strict per-sample merge only
# Campaign root: {campaign_root}
# Private merge container: {merge_container_dir}
# Final sample handoff bundle: {sample_output_dir}
# Automatic DAGMan retry count (shard nodes only): {dagman_retries}
# Generated by generate_efficiency_dag.py
#
"""

SHARD_SUB_TEMPLATE = """\
# shard {shard_index} for {sample}
universe = vanilla
executable = ./run_wrapper.sh

arguments = "{arguments}"

log_dir = logs/jjp_efficiency
output = $(log_dir)/jjp_efficiency_{sample}_{shard_index}_$(Cluster)_$(Process).out
error  = $(log_dir)/jjp_efficiency_{sample}_{shard_index}_$(Cluster)_$(Process).err
log    = $(log_dir)/jjp_efficiency_{sample}_{shard_index}_$(Cluster).log

+JobFlavour = "microcentury"
request_memory = 8000
request_cpus = 1
request_disk = 5G

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
# The manifest is transferred explicitly. The worker receives only its basename.
transfer_input_files = {runtime_tarball},{shard_manifest}

getenv = False
environment = "LCG_VIEW=/cvmfs/sft.cern.ch/lcg/views/LCG_109a/x86_64-el9-gcc13-opt RUNTIME_TARBALL={runtime_tarball_basename}"

use_x509userproxy = True
x509userproxy = {proxy_path}

notification = Error
notify_user = chiw@cern.ch
requirements = (OpSysAndVer =?= "AlmaLinux9")
Queue 1
"""

POST_SUB_TEMPLATE = """\
# merge-only post-processing for {sample}; maps/plots are downstream work
universe = vanilla
executable = ./run_wrapper.sh

arguments = "{arguments}"

log_dir = logs/jjp_efficiency
output = $(log_dir)/post_{sample}_$(Cluster).out
error  = $(log_dir)/post_{sample}_$(Cluster).err
log    = $(log_dir)/post_{sample}_$(Cluster).log

+JobFlavour = "microcentury"
request_memory = 8000
request_cpus = 1
request_disk = 5G

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = {runtime_tarball}

getenv = False
environment = "LCG_VIEW=/cvmfs/sft.cern.ch/lcg/views/LCG_109a/x86_64-el9-gcc13-opt RUNTIME_TARBALL={runtime_tarball_basename}"

use_x509userproxy = True
x509userproxy = {proxy_path}

notification = Error
notify_user = chiw@cern.ch
requirements = (OpSysAndVer =?= "AlmaLinux9")
Queue 1
"""


def _require_safe_token(value: str, label: str) -> str:
    """Reject values unsafe for both Condor submit syntax and run_wrapper.sh."""
    if not value or not _SAFE_TOKEN.fullmatch(value):
        raise ValueError(
            f"{label} must be a non-empty safe token (letters, digits, / . _ : = + @ % -)"
        )
    return value


def _require_readable_file(path: Path, label: str) -> Path:
    path = path.expanduser()
    if not path.is_absolute():
        raise ValueError(f"{label} must be an absolute path: {path}")
    if not path.is_file() or not os.access(path, os.R_OK):
        raise FileNotFoundError(f"{label} is not a readable regular file: {path}")
    _require_safe_token(str(path), label)
    return path.resolve()


def _worker_config_path(config_path: Path) -> str:
    """Return the repository-relative config path available inside the tarball."""
    resolved = config_path.resolve()
    try:
        relative = resolved.relative_to(REPO_ROOT)
    except ValueError as exc:
        raise ValueError(
            "--efficiency-config must be a readable file inside this repository "
            "so the worker runtime tarball contains it"
        ) from exc
    if not resolved.is_file() or not os.access(resolved, os.R_OK):
        raise FileNotFoundError(f"--efficiency-config is not a readable regular file: {resolved}")
    return _require_safe_token(relative.as_posix(), "--efficiency-config")


def _condor_arguments(argv: list[str]) -> str:
    """Encode a validated argv list for Condor's quoted ``arguments`` field."""
    for value in argv:
        _require_safe_token(value, "Condor argument")
    # Accepted values are inert for the legacy unquoted expansion in
    # run_wrapper.sh. shlex.join documents the intended argv boundaries.
    rendered = shlex.join(argv)
    if '"' in rendered or "\n" in rendered or "\r" in rendered:
        raise ValueError("Condor arguments contain unsupported quote/control characters")
    return rendered


def _read_shard_manifest(path: Path, sample: str, shard_index: str) -> None:
    """Statically bind each queue row to its declared sample and shard index."""
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ValueError(f"Invalid shard manifest {path}: {exc}") from exc
    if payload.get("sample") != sample:
        raise ValueError(f"Shard manifest sample mismatch for {path}: expected {sample}")
    if str(payload.get("shard_index")) != shard_index:
        raise ValueError(f"Shard manifest index mismatch for {path}: expected {shard_index}")
    if not isinstance(payload.get("files"), list) or not payload["files"]:
        raise ValueError(f"Shard manifest has no declared files: {path}")


def _shard_args(*, sample: str, shard_index: str, manifest_basename: str,
                output_dir: str, remote_access_mode: str,
                efficiency_backend: str, stage_retries: int,
                copy_timeout: int, worker_timeout: int,
                worker_config: str) -> str:
    return _condor_arguments([
        "run_jjp_efficiency_shard.sh", "--sample", sample,
        "--shard-index", shard_index, "--shard-manifest", manifest_basename,
        "--output-dir", output_dir, "--remote-access-mode", remote_access_mode,
        "--efficiency-backend", efficiency_backend,
        "--stage-retries", str(stage_retries), "--copy-timeout", str(copy_timeout),
        "--worker-timeout", str(worker_timeout), "--tree-path", "auto",
        "--efficiency-config", worker_config, "--config-policy", "strict",
        "--skip-plots",
    ])


def _validate_campaign_contract(*, sample: str, output_dir: Path,
                               runtime_tarball: str, proxy_path: str,
                               tree_path: str, efficiency_config: str | None,
                               config_policy: str | None, efficiency_backend: str,
                               remote_access_mode: str, stage_retries: int,
                               copy_timeout: int, worker_timeout: int,
                               dagman_retries: int, cleanup_shards: bool) -> tuple[Path, Path, Path, Path, str]:
    if not _SAFE_SAMPLE.fullmatch(sample):
        raise ValueError("--sample must contain only letters, digits, and underscores")
    if cleanup_shards:
        raise ValueError("Shard cleanup is prohibited by the campaign safety contract")
    if tree_path != "auto":
        raise ValueError("The campaign requires --tree-path auto")
    if config_policy != "strict":
        raise ValueError("The campaign requires --config-policy strict")
    if not efficiency_config:
        raise ValueError("The campaign requires an explicit --efficiency-config")
    if efficiency_backend != "vectorized":
        raise ValueError("The campaign requires --efficiency-backend vectorized")
    if remote_access_mode not in {"fallback", "direct", "stage"}:
        raise ValueError("--remote-access-mode must be fallback, direct, or stage")
    if stage_retries <= 0:
        raise ValueError("--stage-retries must be positive")
    if copy_timeout < 0 or worker_timeout < 0:
        raise ValueError("--copy-timeout and --worker-timeout must be non-negative")
    if dagman_retries < 0:
        raise ValueError("--dagman-retries must be non-negative")

    runtime_path = _require_readable_file(Path(runtime_tarball), "--runtime-tarball")
    proxy = _require_readable_file(Path(proxy_path), "--proxy-path")
    worker_config = _worker_config_path(Path(efficiency_config))
    if not output_dir.is_absolute():
        raise ValueError("--output-dir must be an absolute campaign root")
    _require_safe_token(str(output_dir), "--output-dir")
    sample_output_dir = output_dir / sample
    merge_container_dir = output_dir / f"_merge_{sample}"
    if sample_output_dir.exists() or merge_container_dir.exists():
        raise FileExistsError(
            "Refusing to reuse an existing per-sample handoff or merge container: "
            f"{sample_output_dir} / {merge_container_dir}"
        )
    return runtime_path, proxy, merge_container_dir, sample_output_dir, worker_config


def build_dag(sample: str, queue_file: Path, output_dir: Path,
              runtime_tarball: str, dag_dir: Path, *, proxy_path: str,
              cleanup_shards: bool = False, remote_access_mode: str = "fallback",
              efficiency_backend: str = "vectorized", stage_retries: int = 3,
              copy_timeout: int = 180, worker_timeout: int = 180,
              tree_path: str = "auto", efficiency_config: str | None = None,
              config_policy: str | None = None, dagman_retries: int = 2) -> Path:
    """Write one sample's safe DAG and return its path without submitting it."""
    queue_file = queue_file.resolve()
    if not queue_file.is_file():
        raise FileNotFoundError(f"Queue file not found: {queue_file}")
    _require_safe_token(str(queue_file), "--queue-file")
    runtime_path, proxy, merge_container_dir, sample_output_dir, worker_config = _validate_campaign_contract(
        sample=sample, output_dir=output_dir, runtime_tarball=runtime_tarball,
        proxy_path=proxy_path, tree_path=tree_path, efficiency_config=efficiency_config,
        config_policy=config_policy, efficiency_backend=efficiency_backend,
        remote_access_mode=remote_access_mode, stage_retries=stage_retries,
        copy_timeout=copy_timeout, worker_timeout=worker_timeout,
        dagman_retries=dagman_retries, cleanup_shards=cleanup_shards,
    )

    shard_entries: list[tuple[str, Path]] = []
    for raw_line in queue_file.read_text(encoding="utf-8").splitlines():
        if not raw_line.strip() or raw_line.lstrip().startswith("#"):
            continue
        parts = raw_line.strip().split(None, 2)
        if len(parts) != 3:
            raise ValueError(f"Malformed queue row: {raw_line!r}")
        row_sample, shard_index, manifest_raw = parts
        if row_sample != sample:
            continue
        if not shard_index.isdigit():
            raise ValueError(f"Shard index must be numeric: {shard_index!r}")
        manifest_path = Path(manifest_raw).resolve()
        _require_readable_file(manifest_path, "shard manifest")
        if not _SAFE_NAME.fullmatch(manifest_path.name):
            raise ValueError(f"Shard manifest basename is unsafe: {manifest_path.name!r}")
        _read_shard_manifest(manifest_path, sample, shard_index)
        shard_entries.append((shard_index, manifest_path))
    if not shard_entries:
        raise RuntimeError(f"No shard entries found for sample {sample} in {queue_file}")
    if len({index for index, _ in shard_entries}) != len(shard_entries):
        raise ValueError(f"Duplicate shard index in queue file for {sample}")

    dag_dir = dag_dir.resolve()
    _require_safe_token(str(dag_dir), "--dag-dir")
    dag_dir.mkdir(parents=True, exist_ok=True)
    shards_dir = output_dir / "shards" / sample
    dag_path = dag_dir / f"dag_{sample}.dag"
    lines: list[str] = [DAG_HEADER.format(
        sample=sample, n_shards=len(shard_entries), campaign_root=output_dir,
        merge_container_dir=merge_container_dir, sample_output_dir=sample_output_dir, dagman_retries=dagman_retries,
    )]
    shard_names: list[str] = []
    for shard_index, manifest_path in shard_entries:
        name = f"SHARD_{shard_index.zfill(4)}"
        shard_names.append(name)
        sub_path = (dag_dir / f"sub_shard_{sample}_{shard_index.zfill(4)}.sub").resolve()
        sub_path.write_text(SHARD_SUB_TEMPLATE.format(
            sample=sample, shard_index=shard_index,
            arguments=_shard_args(
                sample=sample, shard_index=shard_index,
                manifest_basename=manifest_path.name, output_dir=str(output_dir),
                remote_access_mode=remote_access_mode, efficiency_backend=efficiency_backend,
                stage_retries=stage_retries, copy_timeout=copy_timeout,
                worker_timeout=worker_timeout, worker_config=worker_config,
            ), runtime_tarball=runtime_path, runtime_tarball_basename=runtime_path.name,
            shard_manifest=manifest_path, proxy_path=proxy,
        ), encoding="utf-8")
        lines.extend((f"JOB {name} {sub_path}", f"RETRY {name} {dagman_retries}", ""))

    post_sub = (dag_dir / f"sub_post_{sample}.sub").resolve()
    post_sub.write_text(POST_SUB_TEMPLATE.format(
        sample=sample,
        arguments=_condor_arguments([
            "run_jjp_efficiency_merge_only.sh", sample, str(shards_dir), str(merge_container_dir), str(sample_output_dir),
        ]), runtime_tarball=runtime_path, runtime_tarball_basename=runtime_path.name,
        proxy_path=proxy,
    ), encoding="utf-8")
    lines.extend((f"JOB POST {post_sub}", "", "PARENT " + " ".join(shard_names) + " CHILD POST", ""))
    dag_path.write_text("\n".join(lines), encoding="utf-8")
    return dag_path


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate a safe per-sample HTCondor efficiency DAG")
    parser.add_argument("--sample", required=True, help="One checked-in sample key (for example JJP_DPS2_CS)")
    parser.add_argument("--queue-file", required=True, help="Master queue file from prepare_efficiency_shards.py")
    parser.add_argument("--output-dir", required=True, help="Absolute campaign root; generator uses <root>/<sample>")
    parser.add_argument("--runtime-tarball", required=True, help="Readable runtime tarball transferred to every node")
    parser.add_argument("--proxy-path", required=True, help="Readable absolute X.509 proxy path used by HTCondor")
    parser.add_argument("--dag-dir", default=None, help="Directory for DAG output (default: <queue-file parent>/dags)")
    parser.add_argument("--cleanup-shards", action="store_true", help=argparse.SUPPRESS)
    parser.add_argument("--remote-access-mode", default="fallback", choices=("fallback", "direct", "stage"))
    parser.add_argument("--efficiency-backend", default="vectorized", choices=("vectorized", "python-loop"))
    parser.add_argument("--stage-retries", type=int, default=3)
    parser.add_argument("--copy-timeout", type=int, default=180)
    parser.add_argument("--worker-timeout", type=int, default=180)
    parser.add_argument("--tree-path", default="auto")
    parser.add_argument("--efficiency-config", required=True)
    parser.add_argument("--config-policy", choices=("strict", "legacy"), required=True)
    parser.add_argument("--dagman-retries", "--automatic-retry-count", dest="dagman_retries", type=int, default=2,
                        help="Bounded automatic DAGMan retries per shard (default: 2)")
    args = parser.parse_args()
    queue_file = Path(args.queue_file)
    dag_dir = Path(args.dag_dir) if args.dag_dir else (queue_file.parent / "dags")
    dag_path = build_dag(
        sample=args.sample, queue_file=queue_file, output_dir=Path(args.output_dir),
        runtime_tarball=args.runtime_tarball, dag_dir=dag_dir, proxy_path=args.proxy_path,
        cleanup_shards=args.cleanup_shards, remote_access_mode=args.remote_access_mode,
        efficiency_backend=args.efficiency_backend, stage_retries=args.stage_retries,
        copy_timeout=args.copy_timeout, worker_timeout=args.worker_timeout,
        tree_path=args.tree_path, efficiency_config=args.efficiency_config,
        config_policy=args.config_policy, dagman_retries=args.dagman_retries,
    )
    print(f"Wrote DAG: {dag_path}")
    print(f"Automatic DAGMan retries per shard: {args.dagman_retries}")
    print(f"Per-sample merge root: {Path(args.output_dir) / args.sample}")


if __name__ == "__main__":
    main()
